version: '3'
services:
    api-service:
        build:
            context: ./backend
            dockerfile: ./docker-backend.dockerfile
        volumes:
            - ./backend:/app
        restart: always
        ports:
            -   "3013:3000"
        deploy:
            mode: replicated
            replicas: 1
        environment:
            DSN: "host=postgres port=5432 user=testuser password=testpassword dbname=test sslmode=disable timezone=UTC connect_timeout=5"
        depends_on:
            -   postgres

    # frontend-service:
    #     build:
    #         context: ./frontend
    #         dockerfile: ./docker-frontend.dockerfile
    #     # volumes:
    #     #     - ./frontend/.output:/app
    #     restart: always
    #     ports:
    #         -   "3010:3000"
    #     deploy:
    #         mode: replicated
    #         replicas: 1

    postgres:
        image: 'postgres:14.0'
        ports:
            -   "3012:5432"
        restart: always
        deploy:
            mode: replicated
            replicas: 1
        environment:
            POSTGRES_USER: testuser
            POSTGRES_PASSWORD: testpassword
            POSTGRES_DB: test
        volumes:
            -   ./db-data/postgres/:/var/lib/postgresql/data/
