CREATE TABLE
    "clients" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "tel" bigint NOT NULL,
        "provider" INTEGER NOT NULL,
        "tag" text NOT NULL,
        "tz" INTEGER NOT NULL 
    );
    
CREATE TABLE
    "messangers" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "time_start" TIMESTAMP WITH TIME ZONE NOT NULL,
        "time_end" TIMESTAMP WITH TIME ZONE NOT NULL,
        "message_text" text NOT NULL,
        "filter" text NOT NULL
    );
CREATE TABLE
    "messages" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "time_sent" TIMESTAMP WITH TIME ZONE NOT NULL,
        "status" bool default false,
        "messanger_id" INT NOT NULL,
        "client_id" INT NOT NULL
    );

ALTER TABLE "messages"
ADD
    FOREIGN KEY ("messanger_id") REFERENCES "messangers" ("id");
    
ALTER TABLE "messages"
ADD
    FOREIGN KEY ("client_id") REFERENCES "clients" ("id");
